Repository getvoicify/planiphy.com, pull requests merged in 2024-01, with the labels that each got.

#2 feat: add build and deployment pipeline
  .github/workflows/build.yml
  .gitignore
  assets/.DS_Store
  assets/css/main.css
  package.json
  pnpm-lock.yaml
  src/css/main.scss
  src/imgs/hero-img.png
  src/imgs/planiphy.svg
  src/index.html
  src/js/main.js
  vite.config.js
Labels: 5 min review

#1 feat: tablet landscape view
  README.md
  src/css/main.scss
  src/index.html
Labels: enhancement, good first issue, 5 min review

#6 fix: menu CTA to secondary action button
  .gitignore
  src/css/main.scss
  src/index.html
Labels: 1 min review
